/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>

double
calculadora_1(char *host, double v1, double v2, int op)
{
		CLIENT *clnt;
		result  *result_1;
		double _val1=v1;
		double _val2=v2;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORA, CALCULADORA_1, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

		result_1->code=0;

		switch(op){
			case 1:
				result_1 = suma_1(_val1, _val2, clnt);
				if (result_1 == (result *) NULL) {
					clnt_perror (clnt, "call failed");
				}
			break;
			case 2:
				result_1 = restar_1(_val1, _val2, clnt);
				if (result_1 == (result *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			break;
			case 3:
				result_1 = multiplica_1(_val1, _val2, clnt);
				if (result_1 == (result *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			break;
			case 4:
				result_1 = divide_1(_val1, _val2, clnt);
				if (result_1 == (result *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			break;
			default: 
				clnt_perror (clnt, "call failed");
			break;
		}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	int fallo=result_1->code;

	if(fallo > 0){
		printf("\n Algo fue mal, codigo de error: %d \n", fallo);

		if(fallo == -1){
			printf("Division por 0 o valor muy cercano a este");
			exit(1);
		}
	}

	return result_1->result_value;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 5) {
		printf ("usage: %s server_host numero1 signo numero2\n Numero de argumentos pasados: %i \n", argv[0], argc);

		exit (1);
	}
	host = argv[1];

	double val1=atof(argv[2]), val2=atof(argv[4]);
	char aux=argv[3][0];
	int op=-1;

	if(aux=='+')
		op=1;
	else if(aux=='-'){
		op=2;
	}else if(aux=='x'){
		op=3;
	}else if(aux=='/'){
		op=4;
	}

	double resultado;

	if(op!=-1){
		if(op==4){
			double epsilon=0.0000001f;

			if(val2<epsilon && val2>-epsilon){
				printf("\nDividiendo por cero\n");
				exit(1);
			}

		}
		
		resultado=calculadora_1 (host,val1,val2,op);
		printf("\n%f\n",resultado);
		
	}
	else{
		printf("\nFallo en el signo\n");
		exit(1);
	}

	exit (0);
}
